export const FETCH_MAIN_DASHBOARD_REQUEST = 'FETCH_MAIN_DASHBOARD_REQUEST'
export const FETCH_MAIN_DASHBOARD_SUCCESS = 'FETCH_MAIN_DASHBOARD_SUCCESS'
export const FETCH_MAIN_DASHBOARD_FAILURE = 'FETCH_MAIN_DASHBOARD_FAILURE'